esphome:
  name: airleaf-motor-01
  includes:
    - espnow_receiver.h

esp8266:
  board: d1_mini

wifi:
  ssid: !secret wifi_ssid
  password: !secret wifi_password

api:

ota:
  - platform: esphome
    password: !secret ota_password

logger:
  level: DEBUG

# PWM output for motor speed control
output:
  - platform: esp8266_pwm
    pin: D5  # GPIO14 - white wire to F-PWM
    frequency: 1000 Hz  # 1kHz PWM, adjust if needed
    id: motor_pwm_output

# Fan platform for motor control
fan:
  - platform: speed
    output: motor_pwm_output
    name: "BLDC Motor"
    id: bldc_motor
    restore_mode: RESTORE_DEFAULT_OFF

# Tachometer pulse counter
sensor:
  - platform: pulse_counter
    pin:
      number: D6  # GPIO12 - yellow wire to F-FG
      mode:
        input: true
        pullup: true
    name: "Motor RPM"
    id: motor_rpm
    unit_of_measurement: 'RPM'
    accuracy_decimals: 0
    update_interval: 2s
    count_mode:
      rising_edge: INCREMENT
      falling_edge: DISABLE
    filters:
      # Calibration: adjust multiplier based on motor's pulses per revolution
      # Formula: 60 / (pulses_per_revolution * update_interval_seconds)
      # Example: For 2 pulses/rev with 2s update: 60 / (2 * 2) = 15
      - multiply: 30.0
      - sliding_window_moving_average:
          window_size: 5
          send_every: 1

  # Target RPM setpoint from Airleaf controller
  - platform: template
    name: "Target RPM Setpoint"
    id: target_rpm_setpoint_sensor
    unit_of_measurement: 'RPM'
    accuracy_decimals: 0
    icon: "mdi:speedometer-slow"
    lambda: "return id(target_rpm_setpoint);"
    update_interval: 1s

  # Calculated PWM percentage (for monitoring)
  - platform: template
    name: "Motor PWM Percentage"
    id: motor_pwm_percent
    unit_of_measurement: '%'
    accuracy_decimals: 1
    icon: "mdi:percent"
    state_class: measurement

text_sensor:
  # Consolidated ESP-NOW status with MAC and connection state
  - platform: template
    name: "ESP-NOW Status"
    id: espnow_status
    icon: "mdi:access-point-network"
    entity_category: diagnostic

number:
  # Maximum RPM reference for PWM percentage calculation
  # 100% PWM duty cycle = this RPM value
  - platform: template
    name: "Max RPM Reference"
    id: max_rpm_reference
    min_value: 500
    max_value: 3000
    step: 50
    initial_value: 2000
    mode: box
    optimistic: true
    icon: "mdi:speedometer"
    unit_of_measurement: "RPM"
    entity_category: config
    restore_value: true

# Global variables
globals:
  - id: target_rpm_setpoint
    type: int
    restore_value: no
    initial_value: '0'
  - id: sender_mac
    type: uint8_t[6]
    restore_value: no

# ESP-NOW receiver loop
interval:
  - interval: 5s
    then:
      - lambda: |-
          espnow_receiver_loop();
